name: Build & Test
permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Swift
        uses: fwal/setup-swift@v2
        with:
          swift-version: '5.9'

      - name: Show versions
        run: |
          sw_vers
          swift --version

      - name: Build (release)
        run: swift build --configuration release
