name: Build & Test
permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-15
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      # Xcode 16 => macOS 15 SDK
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.*'

      # TOOLCHAINS
      - name: Use default Apple toolchain
        run: |
          echo "TOOLCHAINS=" >> $GITHUB_ENV

      - name: Show versions
        run: |
          set -x
          sw_vers
          xcodebuild -version
          xcodebuild -showsdks | grep macosx || true
          which swift
          swift --version
          echo "TOOLCHAINS=${TOOLCHAINS:-<unset>}"

      - name: Build (verbose)
        env:
          TOOLCHAINS: ""   
        run: |
          set -euxo pipefail
          swift build -c release -v
