name: Release macOS App and DMG

on:
  push:
    tags: ['v*']

permissions:
  contents: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: macos-15           
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4

      # Xcode 16 (macOS 15 SDK). 
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.*'

      - name: Show toolchain & SDKs
        run: |
          set -x
          sw_vers
          xcodebuild -version
          xcodebuild -showsdks | grep macosx || true
          which swift
          swift --version
          echo "TOOLCHAINS=${TOOLCHAINS:-<unset>}"

      # Safety: ensure no custom toolchain is set
      - name: Ensure default Apple toolchain
        run: |
          unset TOOLCHAINS
          echo "TOOLCHAINS cleared"

      - name: Install create-dmg (fast)
        run: |
          export HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_NO_INSTALL_CLEANUP=1
          brew install create-dmg

      - name: Build & Package
        timeout-minutes: 12
        run: |
          set -euxo pipefail
          make dmg
          ls -lah dist || true
          ls -lah . | grep dmg || true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: macos-snipper.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
