name: Release macOS App and DMG

on:
  push:
    tags:
      - 'v*' # Trigger on version tags like v1.0.0

permissions:
  contents: write

jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Show Swift version
        run: |
          sw_vers
          swift --version

      - name: Build App Bundle
        run: |
          make bundle

      - name: Create DMG using hdiutil
        run: |
          echo "Creating DMG..."
          DMG_NAME="macos-snipper.dmg"
          hdiutil create -volname "macos-snipper" \
            -srcfolder ".build/release/macos-snipper.app" \
            -ov -format UDZO "$DMG_NAME"

      - name: Upload DMG to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: macos-snipper.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
