name: Release macOS App and DMG

on:
  push:
    tags:
      - 'v*' # Trigger on version tags like v1.0.0

permissions:
  contents: write # Allow writing to repository contents

jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Show Swift version
        run: |
          sw_vers
          swift --version

      - name: Install create-dmg
        run: |
          brew install create-dmg

      - name: Build app bundle
        run: |
          make bundle

      - name: Create DMG
        run: |
          make dmg

      - name: Upload DMG to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ma
